// @vitest-environment node
/**
 * Zoo / KCL rendering / color **observation** tests.
 *
 * Zoo's glTF output is generated by the external KCL engine (cloud websocket),
 * not by Tau code. We do not own the meshing or material pipeline.
 *
 * `createGeometry` requires a live cloud connection and is intentionally not
 * exercised by the per-kernel unit-test suite. These tests therefore document
 * the **architectural contract** rather than runtime output:
 *
 * 1. The Zoo kernel definition exists and exposes export schemas.
 * 2. Per `docs/policy/color-space-policy.md`, when KCL/Zoo emits a glTF, its
 *    `baseColorFactor` is treated as already-linear (per glTF 2.0 spec).
 *    Any post-processing in Tau MUST NOT re-encode it.
 *
 * If/when a recorded fixture or local KCL evaluator becomes available, this
 * file should be expanded with the same `colorParityCases` matrix used by
 * `replicad-rendering.test.ts` etc.
 *
 * See docs/policy/color-space-policy.md and the research doc on color-space
 * convergence.
 */
import { describe, expect, it } from 'vitest';
import zooKernel from '#kernels/zoo/zoo.kernel.js';

describe('Zoo / KCL — color rendering observation', () => {
  it('exposes a kernel definition with at least one export schema', () => {
    expect(zooKernel.name).toBe('ZooKernel');
    expect(zooKernel.exportSchemas).toBeTruthy();
    const formats = Object.keys(zooKernel.exportSchemas ?? {});
    expect(formats.length).toBeGreaterThan(0);
  });

  it('declares glb as a supported export format (color-bearing)', () => {
    const formats = Object.keys(zooKernel.exportSchemas ?? {});
    expect(formats).toContain('glb');
  });
});
