/**
 * NX Plugin for tsgo (TypeScript Go compiler).
 *
 * Used to automatically infer tsgo typecheck targets for all projects.
 * This replaces the standard @nx/js/typescript plugin for typecheck.
 *
 * @see https://github.com/nicolo-ribaudo/TypeScript/tree/nicolo/nicolo/native-preview
 */
import { dirname, join } from 'node:path';
import { existsSync } from 'node:fs';
import { readJsonFile } from '@nx/devkit';
import type {
  CreateNodesContext,
  CreateNodesContextV2,
  CreateNodesResult,
  CreateNodesV2,
  ProjectConfiguration,
} from '@nx/devkit';

type InputDefinition =
  | { input: string; projects: string | string[] }
  | { input: string; dependencies: true }
  | { input: string }
  | { fileset: string }
  | { runtime: string }
  | { externalDependencies: string[] }
  | { dependentTasksOutputFiles: string; transitive?: boolean }
  | { env: string };

type PackageJson = {
  nx?: {
    namedInputs?: Record<string, Array<string | InputDefinition>>;
  };
};

type TsgoPluginOptions = {
  /**
   * The name of the target to create.
   * @default 'typecheck'
   */
  targetName?: string;

  /**
   * Whether to emit declaration files only (no JS output).
   * @default true
   */
  emitDeclarationOnly?: boolean;
};

/**
 * Get the named inputs available for a project.
 */
function getNamedInputs(
  directory: string,
  context: CreateNodesContext | CreateNodesContextV2,
): Record<string, Array<string | InputDefinition>> {
  const projectJsonPath = join(directory, 'project.json');
  const projectJson: ProjectConfiguration | undefined = existsSync(projectJsonPath)
    ? readJsonFile<ProjectConfiguration>(projectJsonPath)
    : undefined;

  const packageJsonPath = join(directory, 'package.json');
  const packageJson: PackageJson | undefined = existsSync(packageJsonPath) ? readJsonFile(packageJsonPath) : undefined;

  return {
    ...context.nxJsonConfiguration.namedInputs,
    ...packageJson?.nx?.namedInputs,
    ...projectJson?.namedInputs,
  };
}

/**
 * Check if a file exists in the project directory.
 */
function fileExists(workspaceRoot: string, projectRoot: string, filename: string): boolean {
  return existsSync(join(workspaceRoot, projectRoot, filename));
}

/**
 * Check if a directory exists in the project directory.
 */
function dirExists(workspaceRoot: string, projectRoot: string, dirname: string): boolean {
  return existsSync(join(workspaceRoot, projectRoot, dirname));
}

/**
 * Get the source directories for a project based on its tsconfig files.
 */
function getSourcePatterns(workspaceRoot: string, projectRoot: string): string[] {
  const patterns: string[] = [];

  // Common source directories
  const sourceDirectories = ['src', 'lib', 'app'];

  for (const dir of sourceDirectories) {
    if (dirExists(workspaceRoot, projectRoot, dir)) {
      patterns.push(`{projectRoot}/${dir}/**/*.ts`);
      patterns.push(`{projectRoot}/${dir}/**/*.tsx`);
      patterns.push(`{projectRoot}/${dir}/**/*.js`);
      patterns.push(`{projectRoot}/${dir}/**/*.jsx`);
    }
  }

  // If no common directories found, use root patterns
  if (patterns.length === 0) {
    patterns.push('{projectRoot}/**/*.ts');
    patterns.push('{projectRoot}/**/*.tsx');
  }

  return patterns;
}

/**
 * Get additional input patterns for common config files and generated types.
 */
function getAdditionalInputPatterns(workspaceRoot: string, projectRoot: string): string[] {
  const patterns: string[] = [];

  // Vite config files
  const viteConfigs = ['vite.config.ts', 'vite.config.js', 'vitest.config.ts', 'vitest.setup.ts'];
  for (const file of viteConfigs) {
    if (fileExists(workspaceRoot, projectRoot, file)) {
      patterns.push(`{projectRoot}/${file}`);
    }
  }

  // Type declaration files
  if (fileExists(workspaceRoot, projectRoot, 'vite-environment.d.ts')) {
    patterns.push('{projectRoot}/vite-environment.d.ts');
  }

  // React Router types (generated by typegen)
  if (dirExists(workspaceRoot, projectRoot, '.react-router')) {
    patterns.push('{projectRoot}/.react-router/types/**/*');
  }

  // Fumadocs/source types
  if (dirExists(workspaceRoot, projectRoot, '.source')) {
    patterns.push('{projectRoot}/.source/**/*');
  }

  // React Router config
  if (fileExists(workspaceRoot, projectRoot, 'react-router.config.ts')) {
    patterns.push('{projectRoot}/react-router.config.ts');
  }

  // Test files
  if (dirExists(workspaceRoot, projectRoot, 'tests')) {
    patterns.push('{projectRoot}/tests/**/*.ts');
    patterns.push('{projectRoot}/tests/**/*.tsx');
  }

  return patterns;
}

/**
 * Get the tsconfig files that exist in a project.
 */
function getTsConfigInputs(workspaceRoot: string, projectRoot: string): string[] {
  const inputs: string[] = [];
  const tsConfigFiles = [
    'tsconfig.json',
    'tsconfig.app.json',
    'tsconfig.lib.json',
    'tsconfig.spec.json',
    'tsconfig.build.json',
  ];

  for (const file of tsConfigFiles) {
    if (fileExists(workspaceRoot, projectRoot, file)) {
      inputs.push(`{projectRoot}/${file}`);
    }
  }

  return inputs;
}

const createTsgoTarget = (
  configFilePath: string,
  context: CreateNodesContextV2,
  options: TsgoPluginOptions,
): CreateNodesResult | undefined => {
  const projectRoot = dirname(configFilePath);

  // Skip workspace root
  if (projectRoot === '.') {
    return undefined;
  }

  const targetName = options.targetName ?? 'typecheck';
  const emitDeclarationOnly = options.emitDeclarationOnly ?? true;
  const workspaceRoot = context.workspaceRoot;

  const namedInputs = getNamedInputs(join(workspaceRoot, projectRoot), context);
  const sourcePatterns = getSourcePatterns(workspaceRoot, projectRoot);
  const tsConfigInputs = getTsConfigInputs(workspaceRoot, projectRoot);
  const additionalInputPatterns = getAdditionalInputPatterns(workspaceRoot, projectRoot);

  // Build the command
  const commandParts = ['tsgo', '--build'];
  if (emitDeclarationOnly) {
    commandParts.push('--emitDeclarationOnly');
  }
  const command = commandParts.join(' ');

  // Build inputs
  const inputs: Array<string | InputDefinition> = [
    // Package configuration
    '{projectRoot}/package.json',
    // Workspace tsconfig
    '{workspaceRoot}/tsconfig.base.json',
    // Project tsconfig files
    ...tsConfigInputs,
    // Source files
    ...sourcePatterns,
    // Additional config and generated files
    ...additionalInputPatterns,
    // Declaration files from dependencies
    { dependentTasksOutputFiles: '**/*.d.ts' },
    // TypeScript as external dependency
    { externalDependencies: ['typescript'] },
  ];

  // Add production named input if available
  if ('production' in namedInputs) {
    inputs.unshift('^production');
  }

  // Build outputs - declaration files and tsbuildinfo
  const outputs: string[] = [
    // Declaration files
    '{projectRoot}/**/*.d.ts',
    '{projectRoot}/**/*.d.cts',
    '{projectRoot}/**/*.d.mts',
    '{projectRoot}/**/*.d.ts.map',
    '{projectRoot}/**/*.d.cts.map',
    '{projectRoot}/**/*.d.mts.map',
    // Build info
    '{projectRoot}/tsconfig.tsbuildinfo',
    // Out-tsc directories (common pattern)
    '{projectRoot}/out-tsc/**/*.d.ts',
    '{projectRoot}/out-tsc/**/*.tsbuildinfo',
  ];

  // If not declaration only, also output JS files
  if (!emitDeclarationOnly) {
    outputs.push(
      '{projectRoot}/**/*.js',
      '{projectRoot}/**/*.cjs',
      '{projectRoot}/**/*.mjs',
      '{projectRoot}/**/*.jsx',
      '{projectRoot}/**/*.js.map',
      '{projectRoot}/**/*.jsx.map',
    );
  }

  return {
    projects: {
      [projectRoot]: {
        targets: {
          [targetName]: {
            executor: 'nx:run-commands',
            cache: true,
            inputs,
            outputs,
            options: {
              command,
            },
          },
        },
      },
    },
  };
};

export const createNodesV2: CreateNodesV2<TsgoPluginOptions> = [
  '**/tsconfig.json',
  // eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types -- not necessary as already has an explicit return type
  (configFiles, options, context) => {
    const results: Array<[string, CreateNodesResult]> = [];
    const pluginOptions = options ?? {};

    for (const configFile of configFiles) {
      try {
        // Skip node_modules and other non-project directories
        if (configFile.includes('node_modules')) {
          continue;
        }

        const target = createTsgoTarget(configFile, context, pluginOptions);
        if (target) {
          results.push([configFile, target]);
        }
      } catch {
        // Ignore errors for individual projects
      }
    }

    return results;
  },
];

